version: "3"
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=api-med'
      - 'MYSQL_USER=apimed'
      - 'MYSQL_PASSWORD=apimed'
      - 'MYSQL_ROOT_PASSWORD=some_password'
    ports:
      - '3306:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql:3306/api-med
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080